Tracker:AddLayouts("layouts/settings_with_labels.json")
Tracker:AddLayouts("layouts/items_grid.json")
Tracker:AddLayouts("layouts/tabs.json")
Tracker:AddLayouts("layouts/tracker.json")
Tracker:AddLayouts("layouts/broadcast.json")

Tracker:AddLayouts("layouts/warrior_episodes.json")
Tracker:AddLayouts("layouts/thief_episodes.json")
Tracker:AddLayouts("layouts/episode_all.json")

Tracker:AddLayouts("layouts/episode_one_with_labels.json")
Tracker:AddLayouts("layouts/episode_two_with_labels.json")
Tracker:AddLayouts("layouts/episode_three_with_labels.json")
Tracker:AddLayouts("layouts/episode_four_with_labels.json")
Tracker:AddLayouts("layouts/episode_five_with_labels.json")
Tracker:AddLayouts("layouts/episode_six_with_labels.json")