Tracker:AddLocations("locations/Warrior Overworld.json")
Tracker:AddLocations("locations/Warrior Episode 1.json")
Tracker:AddLocations("locations/Warrior Episode 2.json")
Tracker:AddLocations("locations/Warrior Episode 3.json")
Tracker:AddLocations("locations/Warrior Episode 4.json")
Tracker:AddLocations("locations/Warrior Episode 5.json")
Tracker:AddLocations("locations/Warrior Episode 6.json")
Tracker:AddLocations("locations/Thief Overworld.json")
Tracker:AddLocations("locations/Thief Episode 1.json")
Tracker:AddLocations("locations/Thief Episode 2.json")
Tracker:AddLocations("locations/Thief Episode 3.json")
Tracker:AddLocations("locations/Thief Episode 4.json")
Tracker:AddLocations("locations/Thief Episode 5.json")
Tracker:AddLocations("locations/Thief Episode 6.json")
Tracker:AddLocations("locations/Robot Overworld.json")
Tracker:AddLocations("locations/Robot Episode 1.json")
Tracker:AddLocations("locations/Robot Episode 2.json")
Tracker:AddLocations("locations/Robot Episode 3.json")
Tracker:AddLocations("locations/Robot Episode 4.json")
Tracker:AddLocations("locations/Robot Episode 5.json")
Tracker:AddLocations("locations/Robot Episode 6.json")
Tracker:AddLocations("locations/Inventor Overworld.json")
Tracker:AddLocations("locations/Inventor Episode 1.json")
Tracker:AddLocations("locations/Inventor Episode 2.json")
Tracker:AddLocations("locations/Inventor Episode 3.json")
Tracker:AddLocations("locations/Inventor Episode 4.json")
Tracker:AddLocations("locations/Inventor Episode 5.json")
Tracker:AddLocations("locations/Inventor Episode 6.json")